[package]
name = "adsensor"
version = "0.1.0"
edition = "2024"

[dependencies]
kovi.workspace = true
kovi-plugin-expand-napcat = "0.4.0"
config = "0.15.11"
lazy_static = "1.5.0"
serde = { version = "1.0.219", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

